title: Danilo Sambugaro
email: dan.sambugaro@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Informations about the developer Danilo Sambugaro and personal Blog.
permalink: ':title/'
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://dsambugaro.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Author settings
author: Danilo Sambugaro # add your name
author-pic: https://avatars.githubusercontent.com/u/13372649?v=4&s=460
about-author: Estudante de Ciência da Computação na Universidade Tecnológica Federal do Paraná - UTFPR, apreciador do Python e entusiasta de Código Aberto e Linux. Sou um tanto maker, como hobby brinco um pouco com sistemas embarcados, utilizando Raspberry Pi ou Arduino para alguns projetos pessoais.

# Contact links
email: dan.sambugaro@gmail.com # Add your Email address
phone: # Add your Phone number
website: # Add your website, do not add http://
linkedin: dsambugaro # Add your Linkedin handle
github: dsambugaro # Add your Github handle
twitter: '@dsambugaro_' # Add your Twitter handle
facebook: dsambugaro # Add your Facebook handle
instagram: dsambugaro # Add your Instagram handle
pinterest: # Add your Pinterest handle

# Newsletter
mailchimp: # Add your MailChimp form identifier.

# Disqus
discus_identifier: dsambugaro-blog # Add your discus identifier

# Tracker
analytics: UA-113720826-1 # Google Analytics

# Build settings
markdown: kramdown
plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap

include: [_pages]
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
